
(function(){'use strict';var app=angular.module('isLocalization',[]),replaceText,EVENT_RESOURCE_FILE_LOADED='isLocalize:resourceFileLoaded',EVENT_REQUESTED_RESOURCE_NOT_FOUND='isLocalize:resourceFileNotFound',EVENT_DEFAULT_RESOURCE_NOT_FOUND='isLocalize:CouldNotFindDefault';replaceText=function(str,replacements){var i,target;for(i=0;i<replacements.length;i++){target='{'+(i)+'}';str=str.replace(target,replacements[i].toString().replace('$','$$$$'));}
return str;};app.provider('isLocalize',function(){this.baseUrl='/';this.language='en-us';this.cache={};this.loadResourceOnInit=false;this.$get=['$http','$rootScope','$window','$filter',function($http,$rootScope,$window){var defaultBaseUrl=this.baseUrl,defaultLanguage=this.language,defaultCache=this.cache,deriveLanguage,localize;deriveLanguage=function(){var isAndroidDevice=/android.*\W(\w\w)-(\w\w)\W/i,nav=$window.navigator,language;if(nav.userAgent&&nav.userAgent.match(isAndroidDevice)){language=nav.userAgent.match(isAndroidDevice);}else{language=nav.userLanguage||nav.language;}
return language;};localize={url:null,baseUrl:defaultBaseUrl,language:defaultLanguage,dictionary:[],cache:defaultCache,loadDictionary:function(lang,dictionary){var fromCache=false;if(!this.cache[this.language]){this.language=lang;this.dictionary=dictionary;this.cache[lang]=dictionary;}else{if(lang){this.language=lang;}
this.dictionary=this.cache[this.language];fromCache=true;}
$rootScope.$broadcast(EVENT_RESOURCE_FILE_LOADED,fromCache);},requestResourceFile:function(){if(this.cache[this.language]){return this.loadDictionary();}
var url=this.url||this.inferUrl(),successFn,errorFn,options;options={method:'GET',url:url,cache:false};successFn=this._consumeResourceFile.bind(this);errorFn=function(){if(this.language!=='default'){this.language='default';this.requestResourceFile();$rootScope.$broadcast(EVENT_REQUESTED_RESOURCE_NOT_FOUND);}else{$rootScope.$broadcast(EVENT_DEFAULT_RESOURCE_NOT_FOUND);}}.bind(this);$http(options).success(successFn).error(errorFn);},inferUrl:function(){return[this.baseUrl,'locale_',this.language.toLowerCase(),'.json'].join('');},getLocalizedString:function(key){var value='',i;if(Array.isArray(this.dictionary)&&this.dictionary.length>0){for(i=0;i<this.dictionary.length;i++){if(this.dictionary[i].key===key){value=this.dictionary[i].value;break;}}}
return value;},setLanguage:function(lang){this.language=lang;this.url=this.inferUrl();this.requestResourceFile();},_consumeResourceFile:function(data){this.loadDictionary(this.language,data);}};if(this.loadResourceOnInit===true){localize.requestResourceFile();}
return localize;}];this.setOptions=function(options){for(var key in options){if(options.hasOwnProperty(key)&&key in this){this[key]=options[key];}}};});app.filter('i18n',['isLocalize',function(isLocalize){return function(key){var args=Array.prototype.slice.call(arguments,1),text=isLocalize.getLocalizedString(key);if(text!==''&&args.length>0){text=replaceText(text,args);}
return text;};}]);app.directive('i18n',['isLocalize','$compile',function(isLocalize,$compile){var i18nDirective={restrict:'A',link:function(scope,elm,attrs){scope.$on(EVENT_RESOURCE_FILE_LOADED,function(){i18nDirective.updateText(scope,elm,attrs.i18n);});attrs.$observe('i18n',function(){i18nDirective.updateText(scope,elm,attrs.i18n);});},updateText:function(scope,el,token){var values=token.split('|'),tag;if(values.length>=1){tag=isLocalize.getLocalizedString(values[0]);if(tag!==''){if(values.length>1){values.shift();tag=replaceText(tag,values);}
el.html(tag);el.removeAttr('data-i18n');if(tag.indexOf('ng-click')>-1){$compile(el)(scope);}}}}};return i18nDirective;}]);}());